name: Run XUnit Tests

on:
  # Trigger the workflow when a pull request is opened/updated to the 'main' branch
  pull_request:
    branches:
      - main

jobs:
  test:
    # Run on the latest Ubuntu environment provided by GitHub Actions
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Set up the .NET SDK version 9.0
    - name: Setup .NET 9.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x' # Use the latest patch version of .NET 9.0

    # Restore NuGet packages for the entire solution
    # This ensures all project dependencies are available before building/testing
    - name: Restore Dependencies
      run: dotnet restore photographers_story_backend.sln

    # Build the entire solution to ensure everything compiles correctly
    - name: Build Solution
      run: dotnet build photographers_story_backend.sln --no-restore

    # Run the XUnit tests in the 'Tests' project
    # The --verbosity normal flag provides standard output for test results
    - name: Run Tests
      run: dotnet test Tests/Tests.csproj --verbosity normal --no-build --configuration Release